# Last line of defence — validates LLM answers before they reach the user.
"""
Position in the pipeline:
    response_generator.py → [verifier.py] → user

Single responsibility:
    Take a GenerationResult, fact-check the answer against the context
    that produced it, and return a VerificationResult the caller can act on.

Why a separate verifier module?
    Defence in depth. The prompt-level guardrails in prompts.py instruct
    the LLM to only use the provided context. But LLMs don't always follow
    instructions — especially on edge cases. The verifier is an independent
    second pass that catches what the prompt missed.

    This is the "LLM-as-judge" pattern:
        - A FIRST LLM call generates the answer        (response_generator.py)
        - A SECOND LLM call checks that answer         (verifier.py)
    The checker uses GUARDRAIL_PROMPT, which asks for a structured
    JSON verdict: PASS / FAIL / UNCERTAIN

What lives here:
    VerificationResult  → dataclass holding verdict + explanation + safe answer
    verify()            → main entry point, called after generate()
    _parse_verdict()    → converts raw JSON from LLM into a clean verdict
    _build_safe_answer()→ decides what to return to the user based on verdict

Verdict meanings:
    PASS      → answer is fully grounded in context → return as-is
    FAIL      → answer contains unsupported claims  → replace with refusal
    UNCERTAIN → context is ambiguous                → return with a caveat
"""

from dataclasses import dataclass, field

from app.generation.prompts import get_prompt
from app.generation.llm import invoke_json
from app.generation.response_generator import GenerationResult
from app.utils.helpers import truncate_text
from app.utils.logger import get_logger

logger = get_logger(__name__)
# __name__ here is "app.validation.verifier"


# CONSTANTS 

# Valid verdicts the guardrail LLM can return
VALID_VERDICTS = {"PASS", "FAIL", "UNCERTAIN"}

# What the user sees when the answer fails verification.
# Hardcoded so it is NEVER generated by the LLM — it is a deterministic,
# rule-based override. This is critical for financial compliance.
FAIL_RESPONSE = (
    "I was unable to verify this answer against your documents. "
    "The response may contain information not present in the provided context. "
    "Please consult the source documents directly."
)

# What gets appended to UNCERTAIN answers — a caveat, not a replacement.
UNCERTAIN_CAVEAT = (
    "\n\n⚠️ Note: The source documents were ambiguous on this point. "
    "Please verify this answer against the original documents."
)


# VERIFICATION RESULT 

@dataclass
class VerificationResult:
    """
    The output of a verification pass on a GenerationResult.

    Attributes:
        verdict:        "PASS", "FAIL", "UNCERTAIN", or "SKIPPED"
                        SKIPPED means verification was bypassed
                        (e.g. the generation used the fallback prompt —
                        nothing to verify if there was no context).
        explanation:    One sentence from the guardrail LLM explaining
                        why it gave this verdict.
        safe_answer:    The answer that should be shown to the user.
                        - PASS      → original answer unchanged
                        - FAIL      → replaced with FAIL_RESPONSE
                        - UNCERTAIN → original answer + UNCERTAIN_CAVEAT
                        - SKIPPED   → original answer unchanged
        sources:        Passed through from GenerationResult for citations.
        original_answer: The raw answer before any safety override.
                         Kept for logging and debugging.
        metadata:       Timing and model info from both generation passes.
    """
    verdict: str
    explanation: str
    safe_answer: str
    sources: list[str]
    original_answer: str
    metadata: dict = field(default_factory=dict)

    def passed(self) -> bool:
        """True if the answer is safe to show as-is."""
        return self.verdict in {"PASS", "SKIPPED"}

    def __repr__(self) -> str:
        preview = self.safe_answer[:80].replace("\n", " ")
        return (
            f"VerificationResult("
            f"verdict={self.verdict!r}, "
            f"sources={self.sources}, "
            f"answer={preview!r})"
        )


# INTERNAL HELPERS 

def _parse_verdict(raw: dict | list | None) -> tuple[str, str]:
    """
    Extract verdict and explanation from the guardrail LLM's JSON response.

    The guardrail prompt asks for:
        {"verdict": "PASS" | "FAIL" | "UNCERTAIN", "explanation": "..."}

    This function handles everything that can go wrong:
        - raw is None       (invoke_json failed to parse)
        - verdict missing   (LLM didn't follow the format)
        - verdict invalid   (LLM returned something unexpected)

    In all failure cases we return "UNCERTAIN" — we don't know if the
    answer is safe, so we treat it conservatively.

    Args:
        raw: Parsed JSON from invoke_json(), or None on parse failure.

    Returns:
        Tuple of (verdict, explanation) — both are always strings.
    """
    if raw is None:
        logger.warning(
            "Guardrail LLM returned unparseable JSON — defaulting to UNCERTAIN"
        )
        return "UNCERTAIN", "Verification response could not be parsed."

    if not isinstance(raw, dict):
        logger.warning(
            "Guardrail response was not a dict (got %s) — defaulting to UNCERTAIN",
            type(raw).__name__,
        )
        return "UNCERTAIN", "Verification response had unexpected format."

    verdict     = str(raw.get("verdict", "")).strip().upper()
    explanation = str(raw.get("explanation", "No explanation provided.")).strip()

    if verdict not in VALID_VERDICTS:
        logger.warning(
            "Guardrail returned unknown verdict %r — defaulting to UNCERTAIN",
            verdict,
        )
        return "UNCERTAIN", explanation or "Unknown verdict returned."

    return verdict, explanation


def _build_safe_answer(
    verdict: str,
    original_answer: str,
) -> str:
    """
    Apply the verdict to produce the answer that reaches the user.

    This is intentionally rule-based — NOT generated by the LLM.
    The override responses (FAIL_RESPONSE, UNCERTAIN_CAVEAT) are
    hardcoded constants defined at the top of this file.

    Why rule-based and not LLM-generated?
        If the LLM hallucinated the answer, we can't trust the same LLM
        to generate a safe refusal. The fallback must be deterministic.
        This is what "rule-based overrides" means in the job description.

    Args:
        verdict:         One of PASS / FAIL / UNCERTAIN.
        original_answer: The draft answer from response_generator.py.

    Returns:
        The answer string to show the user.
    """
    if verdict == "PASS":
        return original_answer

    if verdict == "FAIL":
        logger.warning(
            "Answer FAILED verification — replacing with safe refusal. "
            "Original: %r",
            truncate_text(original_answer, 120),
        )
        return FAIL_RESPONSE

    if verdict == "UNCERTAIN":
        logger.info(
            "Answer is UNCERTAIN — appending caveat to original answer."
        )
        return original_answer + UNCERTAIN_CAVEAT

    # Should never reach here — _parse_verdict() guarantees valid verdicts
    return original_answer


# MAIN ENTRY POINT 

def verify(result: GenerationResult) -> VerificationResult:
    """
    Verify a GenerationResult before it reaches the user.

    This is the function main.py calls after generate() or
    generate_with_history(). It is the final gate in the pipeline.

    Steps:
        1. Skip verification if the fallback prompt was used
           (no context = nothing to fact-check against)
        2. Build GUARDRAIL_PROMPT messages with context + question + answer
        3. Call invoke_json() to get a structured verdict
        4. Parse the verdict with _parse_verdict()
        5. Build the safe answer with _build_safe_answer()
        6. Return a VerificationResult

    Args:
        result: A GenerationResult from response_generator.generate()

    Returns:
        VerificationResult with a safe_answer ready to show the user.

    Example:
        gen_result  = generate("What was my balance in January?")
        ver_result  = verify(gen_result)
        print(ver_result.safe_answer)   # what the user sees
        print(ver_result.verdict)       # PASS / FAIL / UNCERTAIN / SKIPPED
    """
    logger.info(
        "Starting verification | question: %r | sources: %s",
        truncate_text(result.question, 80),
        result.sources,
    )

    # Step 1: Skip if fallback was used 
    # The fallback prompt (NO_CONTEXT_PROMPT) fires when retrieval found
    # nothing. There is no context to verify against, so we skip the
    # guardrail and pass the answer through unchanged.
    # The fallback answer is already a safe refusal by design.
    if result.used_fallback:
        logger.info(
            "Skipping verification — generation used fallback prompt "
            "(no retrieved context to check against)"
        )
        return VerificationResult(
            verdict="SKIPPED",
            explanation="No context was retrieved — fallback response is inherently safe.",
            safe_answer=result.answer,
            sources=result.sources,
            original_answer=result.answer,
            metadata=result.metadata,
        )

    # Step 2: Build guardrail messages 
    # GUARDRAIL_PROMPT needs three variables:
    #   {context}  → the same context the answer was generated from
    #   {question} → the original question
    #   {answer}   → the draft answer to verify
    guardrail_prompt   = get_prompt("guardrail")
    guardrail_messages = guardrail_prompt.format_messages(
        context=result.context,
        question=result.question,
        answer=result.answer,
    )

    logger.debug(
        "Guardrail prompt built | context=%d chars | answer=%d chars",
        len(result.context),
        len(result.answer),
    )

    # Step 3: Invoke the guardrail LLM to get a verdict
    # invoke_json() calls the LLM and parses the response as JSON.
    # Returns None if parsing fails — _parse_verdict() handles that.
    raw_verdict = invoke_json(guardrail_messages)

    # Step 4: Parse the verdict and explanation from the raw LLM response
    verdict, explanation = _parse_verdict(raw_verdict)

    logger.info(
        "Verdict: %s | explanation: %s",
        verdict,
        explanation,
    )

    # Step 5: Build the safe answer based on the verdict
    # Rule-based override — deterministic, not LLM-generated.
    safe_answer = _build_safe_answer(verdict, result.answer)

    # Step 6: Return a structured VerificationResult for the caller to act on
    return VerificationResult(
        verdict=verdict,
        explanation=explanation,
        safe_answer=safe_answer,
        sources=result.sources,
        original_answer=result.answer,
        metadata={
            **result.metadata,
            "verified": True,
            "verdict": verdict,
        },
    )